preset: preset1
header:
  background: '#312f38'
  background-image: ''
  text-color: '#eceeef'
utility:
  background: '#ffffff'
  text-color: '#020202'
above:
  background: '#020202'
  text-color: '#ffffff'
testimonials:
  background: '#ffffff'
  background-image: ''
  background-overlay: disabled
  text-color: '#020202'
